version: "3.3"
services:
  stepwise:
    image: stepwisehq/stepwise
    ports:
    - "5000:5000"
    links:
    - postgres
    environment:
      StepWise_ConnectionStrings__DefaultConnection: Host=postgres;Database=stepwise;Username=postgres;Password=password;Minimum Pool Size=5;Maximum Pool Size=5;Application Name=StepWise;Max Auto Prepare=50;Auto Prepare Min Usages=1
      StepWise_Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    command: "./StepWise.Server"
  postgres:
    image: postgres:14
    expose:
    - "5432"
    volumes:
      - stepwise-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    shm_size: 1g


volumes: { stepwise-postgres: {}}
